apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  # This optional configuration block can be used to inject HCL into any
  # workspace that uses this provider config, for example to setup Terraform
  # providers.
  configuration: |
      // Modules _must_ use remote state. The provider does not persist state.
      terraform {
        backend "kubernetes" {
          secret_suffix     = "providerconfig-default"
          namespace         = "default"
          config_path       = "~/.kube/config"
        }
      }
